// Positive Case: Depth 100
int test_func(int val) {
    int x = 0; // Initialized at declaration
    for (int i1 = 0; i1 < 5; ++i1) {
        while (val < 102) {
            val++;
            if (val > 3) {
                for (int i4 = 0; i4 < 5; ++i4) {
                    while (val < 105) {
                        val++;
                        if (val > 6) {
                            for (int i7 = 0; i7 < 5; ++i7) {
                                while (val < 108) {
                                    val++;
                                    if (val > 9) {
                                        for (int i10 = 0; i10 < 5; ++i10) {
                                            while (val < 111) {
                                                val++;
                                                if (val > 12) {
                                                    for (int i13 = 0; i13 < 5; ++i13) {
                                                        while (val < 114) {
                                                            val++;
                                                            if (val > 15) {
                                                                for (int i16 = 0; i16 < 5; ++i16) {
                                                                    while (val < 117) {
                                                                        val++;
                                                                        if (val > 18) {
                                                                            for (int i19 = 0; i19 < 5; ++i19) {
                                                                                while (val < 120) {
                                                                                    val++;
                                                                                    if (val > 21) {
                                                                                        for (int i22 = 0; i22 < 5; ++i22) {
                                                                                            while (val < 123) {
                                                                                                val++;
                                                                                                if (val > 24) {
                                                                                                    for (int i25 = 0; i25 < 5; ++i25) {
                                                                                                        while (val < 126) {
                                                                                                            val++;
                                                                                                            if (val > 27) {
                                                                                                                for (int i28 = 0; i28 < 5; ++i28) {
                                                                                                                    while (val < 129) {
                                                                                                                        val++;
                                                                                                                        if (val > 30) {
                                                                                                                            for (int i31 = 0; i31 < 5; ++i31) {
                                                                                                                                while (val < 132) {
                                                                                                                                    val++;
                                                                                                                                    if (val > 33) {
                                                                                                                                        for (int i34 = 0; i34 < 5; ++i34) {
                                                                                                                                            while (val < 135) {
                                                                                                                                                val++;
                                                                                                                                                if (val > 36) {
                                                                                                                                                    for (int i37 = 0; i37 < 5; ++i37) {
                                                                                                                                                        while (val < 138) {
                                                                                                                                                            val++;
                                                                                                                                                            if (val > 39) {
                                                                                                                                                                for (int i40 = 0; i40 < 5; ++i40) {
                                                                                                                                                                    while (val < 141) {
                                                                                                                                                                        val++;
                                                                                                                                                                        if (val > 42) {
                                                                                                                                                                            for (int i43 = 0; i43 < 5; ++i43) {
                                                                                                                                                                                while (val < 144) {
                                                                                                                                                                                    val++;
                                                                                                                                                                                    if (val > 45) {
                                                                                                                                                                                        for (int i46 = 0; i46 < 5; ++i46) {
                                                                                                                                                                                            while (val < 147) {
                                                                                                                                                                                                val++;
                                                                                                                                                                                                if (val > 48) {
                                                                                                                                                                                                    for (int i49 = 0; i49 < 5; ++i49) {
                                                                                                                                                                                                        while (val < 150) {
                                                                                                                                                                                                            val++;
                                                                                                                                                                                                            if (val > 51) {
                                                                                                                                                                                                                for (int i52 = 0; i52 < 5; ++i52) {
                                                                                                                                                                                                                    while (val < 153) {
                                                                                                                                                                                                                        val++;
                                                                                                                                                                                                                        if (val > 54) {
                                                                                                                                                                                                                            for (int i55 = 0; i55 < 5; ++i55) {
                                                                                                                                                                                                                                while (val < 156) {
                                                                                                                                                                                                                                    val++;
                                                                                                                                                                                                                                    if (val > 57) {
                                                                                                                                                                                                                                        for (int i58 = 0; i58 < 5; ++i58) {
                                                                                                                                                                                                                                            while (val < 159) {
                                                                                                                                                                                                                                                val++;
                                                                                                                                                                                                                                                if (val > 60) {
                                                                                                                                                                                                                                                    for (int i61 = 0; i61 < 5; ++i61) {
                                                                                                                                                                                                                                                        while (val < 162) {
                                                                                                                                                                                                                                                            val++;
                                                                                                                                                                                                                                                            if (val > 63) {
                                                                                                                                                                                                                                                                for (int i64 = 0; i64 < 5; ++i64) {
                                                                                                                                                                                                                                                                    while (val < 165) {
                                                                                                                                                                                                                                                                        val++;
                                                                                                                                                                                                                                                                        if (val > 66) {
                                                                                                                                                                                                                                                                            for (int i67 = 0; i67 < 5; ++i67) {
                                                                                                                                                                                                                                                                                while (val < 168) {
                                                                                                                                                                                                                                                                                    val++;
                                                                                                                                                                                                                                                                                    if (val > 69) {
                                                                                                                                                                                                                                                                                        for (int i70 = 0; i70 < 5; ++i70) {
                                                                                                                                                                                                                                                                                            while (val < 171) {
                                                                                                                                                                                                                                                                                                val++;
                                                                                                                                                                                                                                                                                                if (val > 72) {
                                                                                                                                                                                                                                                                                                    for (int i73 = 0; i73 < 5; ++i73) {
                                                                                                                                                                                                                                                                                                        while (val < 174) {
                                                                                                                                                                                                                                                                                                            val++;
                                                                                                                                                                                                                                                                                                            if (val > 75) {
                                                                                                                                                                                                                                                                                                                for (int i76 = 0; i76 < 5; ++i76) {
                                                                                                                                                                                                                                                                                                                    while (val < 177) {
                                                                                                                                                                                                                                                                                                                        val++;
                                                                                                                                                                                                                                                                                                                        if (val > 78) {
                                                                                                                                                                                                                                                                                                                            for (int i79 = 0; i79 < 5; ++i79) {
                                                                                                                                                                                                                                                                                                                                while (val < 180) {
                                                                                                                                                                                                                                                                                                                                    val++;
                                                                                                                                                                                                                                                                                                                                    if (val > 81) {
                                                                                                                                                                                                                                                                                                                                        for (int i82 = 0; i82 < 5; ++i82) {
                                                                                                                                                                                                                                                                                                                                            while (val < 183) {
                                                                                                                                                                                                                                                                                                                                                val++;
                                                                                                                                                                                                                                                                                                                                                if (val > 84) {
                                                                                                                                                                                                                                                                                                                                                    for (int i85 = 0; i85 < 5; ++i85) {
                                                                                                                                                                                                                                                                                                                                                        while (val < 186) {
                                                                                                                                                                                                                                                                                                                                                            val++;
                                                                                                                                                                                                                                                                                                                                                            if (val > 87) {
                                                                                                                                                                                                                                                                                                                                                                for (int i88 = 0; i88 < 5; ++i88) {
                                                                                                                                                                                                                                                                                                                                                                    while (val < 189) {
                                                                                                                                                                                                                                                                                                                                                                        val++;
                                                                                                                                                                                                                                                                                                                                                                        if (val > 90) {
                                                                                                                                                                                                                                                                                                                                                                            for (int i91 = 0; i91 < 5; ++i91) {
                                                                                                                                                                                                                                                                                                                                                                                while (val < 192) {
                                                                                                                                                                                                                                                                                                                                                                                    val++;
                                                                                                                                                                                                                                                                                                                                                                                    if (val > 93) {
                                                                                                                                                                                                                                                                                                                                                                                        for (int i94 = 0; i94 < 5; ++i94) {
                                                                                                                                                                                                                                                                                                                                                                                            while (val < 195) {
                                                                                                                                                                                                                                                                                                                                                                                                val++;
                                                                                                                                                                                                                                                                                                                                                                                                if (val > 96) {
                                                                                                                                                                                                                                                                                                                                                                                                    for (int i97 = 0; i97 < 5; ++i97) {
                                                                                                                                                                                                                                                                                                                                                                                                        while (val < 198) {
                                                                                                                                                                                                                                                                                                                                                                                                            val++;
                                                                                                                                                                                                                                                                                                                                                                                                            if (val > 99) {
                                                                                                                                                                                                                                                                                                                                                                                                                x = 1; // Assignment at depth 100
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                            }
                                                                                                                                                                                                        }
                                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return x;
}
